classDiagram

namespace PkgUtilisateurs {
  class Formateur 
  class Apprenant
  class  Groupe 
  class  NivaeuScholaire
  class Specialite
}



namespace pkg_authentification {
class User
}



class Apprenant {
    + id: int 
    + nom: string 
    + prenom: string 
    + prenom_arab: string
    + nom_arab: string
    + tele_num: string
    + profile_image: string
    + date_inscription: Date
    + cin: string,
    + adresse: string,
}

class Formateur {
    + id: int 
    + nom: string 
    + prenom: string 
    + prenom_arab: string
    + nom_arab: string
    + tele_num: string
    + profile_image: string
}


class Groupe {
  +  id: int
  +  nom: string
  +  description: text
}


class Specialite {
  +  id: int
  +  nom: string
  +  description: text
}


class NivaeuScholaire {
  +  id: int
  +  nom: string
  +  description: text
}


User "1" <-- "1" Formateur : "compte"
User "1" <-- "1" Apprenant : "compte"
Apprenant "*" --> "*" Groupe 
Formateur "*" --> "*" Groupe
Formateur "*" --> "*" Specialite
Apprenant "*" --> "1" NivaeuScholaire
